-- Add the shelter each pet is waiting at.
--
-- Done in three steps so this also applies to a database that already holds
-- pets: a bare ADD COLUMN ... NOT NULL would be rejected for the existing
-- rows. The backfill mirrors shelters.ts, so no re-seed is needed.
ALTER TABLE "pets" ADD COLUMN "shelter" text NOT NULL DEFAULT 'Pawspot Partner Shelter';--> statement-breakpoint

UPDATE "pets" SET "shelter" = CASE "location"
    WHEN 'Albuquerque, NM' THEN 'High Desert Animal Haven'
    WHEN 'Anchorage, AK' THEN 'Northern Lights Animal Rescue'
    WHEN 'Ann Arbor, MI' THEN 'Huron Valley Pet Refuge'
    WHEN 'Athens, GA' THEN 'Classic City Animal Shelter'
    WHEN 'Austin, TX' THEN 'Barton Springs Animal Rescue'
    WHEN 'Baltimore, MD' THEN 'Charm City Animal Shelter'
    WHEN 'Bangor, ME' THEN 'Penobscot Pet Rescue'
    WHEN 'Berkeley, CA' THEN 'Bayside Animal Friends'
    WHEN 'Boise, ID' THEN 'Foothills Animal Shelter'
    WHEN 'Boston, MA' THEN 'Beacon Hill Animal Rescue'
    WHEN 'Boulder, CO' THEN 'Flatirons Animal Sanctuary'
    WHEN 'Brooklyn, NY' THEN 'Brownstone Pet Rescue'
    WHEN 'Burlington, VT' THEN 'Green Mountain Animal Shelter'
    WHEN 'Charleston, SC' THEN 'Lowcountry Animal Rescue'
    WHEN 'Chicago, IL' THEN 'Lakeshore Animal Shelter'
    WHEN 'Cleveland, OH' THEN 'Cuyahoga Pet Rescue'
    WHEN 'Columbus, OH' THEN 'Scioto Valley Animal Shelter'
    WHEN 'Denver, CO' THEN 'Mile High Animal Rescue'
    WHEN 'Detroit, MI' THEN 'Motor City Animal Refuge'
    WHEN 'Duluth, MN' THEN 'Lake Superior Animal Rescue'
    WHEN 'Flagstaff, AZ' THEN 'Ponderosa Pet Rescue'
    WHEN 'Fort Lauderdale, FL' THEN 'Las Olas Animal Rescue'
    WHEN 'Hartford, CT' THEN 'Charter Oak Animal Shelter'
    WHEN 'Honolulu, HI' THEN 'Aloha Animal Sanctuary'
    WHEN 'Kansas City, MO' THEN 'Crossroads Animal Shelter'
    WHEN 'Lancaster, PA' THEN 'Conestoga Animal Refuge'
    WHEN 'Las Vegas, NV' THEN 'Mojave Pet Rescue'
    WHEN 'Lexington, KY' THEN 'Bluegrass Animal Shelter'
    WHEN 'Los Angeles, CA' THEN 'Silver Lake Animal Rescue'
    WHEN 'Louisville, KY' THEN 'Ohio River Animal Shelter'
    WHEN 'Madison, WI' THEN 'Four Lakes Animal Refuge'
    WHEN 'Memphis, TN' THEN 'Beale Street Animal Rescue'
    WHEN 'Miami, FL' THEN 'Biscayne Bay Pet Rescue'
    WHEN 'Milwaukee, WI' THEN 'Cream City Animal Shelter'
    WHEN 'Minneapolis, MN' THEN 'North Star Animal Rescue'
    WHEN 'Nashville, TN' THEN 'Music City Animal Shelter'
    WHEN 'New Orleans, LA' THEN 'Bayou Animal Rescue'
    WHEN 'Newark, NJ' THEN 'Ironbound Animal Shelter'
    WHEN 'Omaha, NE' THEN 'Prairie Pet Rescue'
    WHEN 'Orlando, FL' THEN 'Citrus Grove Animal Shelter'
    WHEN 'Phoenix, AZ' THEN 'Sonoran Animal Rescue'
    WHEN 'Pittsburgh, PA' THEN 'Three Rivers Animal Shelter'
    WHEN 'Portland, ME' THEN 'Casco Bay Animal Rescue'
    WHEN 'Portland, OR' THEN 'Rose City Animal Shelter'
    WHEN 'Providence, RI' THEN 'Narragansett Pet Rescue'
    WHEN 'Raleigh, NC' THEN 'Oak City Animal Shelter'
    WHEN 'Richmond, VA' THEN 'James River Animal Rescue'
    WHEN 'Sacramento, CA' THEN 'Delta Animal Shelter'
    WHEN 'Salem, MA' THEN 'Witch City Animal Rescue'
    WHEN 'San Diego, CA' THEN 'Sunset Cliffs Animal Rescue'
    WHEN 'San Francisco, CA' THEN 'Golden Gate Animal Rescue'
    WHEN 'San Jose, CA' THEN 'Valley Oak Animal Shelter'
    WHEN 'Santa Fe, NM' THEN 'Sangre de Cristo Pet Refuge'
    WHEN 'Sarasota, FL' THEN 'Siesta Key Animal Shelter'
    WHEN 'Savannah, GA' THEN 'Spanish Moss Animal Rescue'
    WHEN 'Seattle, WA' THEN 'Puget Sound Animal Rescue'
    WHEN 'Spokane, WA' THEN 'Inland Northwest Animal Shelter'
    WHEN 'Tampa, FL' THEN 'Bayshore Animal Rescue'
    WHEN 'Tucson, AZ' THEN 'Saguaro Pet Rescue'
    WHEN 'Tulsa, OK' THEN 'Red Dirt Animal Shelter'
    ELSE "shelter"
  END;--> statement-breakpoint

ALTER TABLE "pets" ALTER COLUMN "shelter" DROP DEFAULT;
